CREATE EXTENSION IF NOT EXISTS citext;

ALTER TABLE users ALTER COLUMN first_name TYPE CITEXT;
ALTER TABLE users ALTER COLUMN last_name TYPE CITEXT;
ALTER TABLE users ALTER COLUMN username TYPE CITEXT;
ALTER TABLE users ALTER COLUMN email TYPE CITEXT;
